### ISSUE TITLE
Clarify usage in README

### ISSUE THREAD

**Issue by febeling** [nettofarah/axios-vcr#6]
The README says

> All you need to do is [...] wrap your axios code in a VCR.use call.

and then the example code didn't use any code like that, `VCR.use`?

I assume this is due to API changes. 

Is it bounding by `mountCassette` and `ejectCassette` instead these days?

**Comment by nettofarah** [comment]
Hey, @febeling 
I think you're right.

I haven't used this project in a while, so I think I kind of forgot to update the docs 😅 

`mount|eject` should be the way to go
